### ISSUE TITLE
Echo is turned off, upon exit

### ISSUE THREAD

**Issue by CharlesAMoss** [cheddar-lang/syncprompt#1]
issue: Upon exit of my node app my typed text is invisible. My guess is echo gets turn off. I think I found where this happens: 

in  index.js on line 13:
sync_prompt.set_echo(false);

---
If I comment this out, after exit I can see my typed text. 
If I do not comment this out I need to type 'reset' or 'stty echo' or my typed text will be invisible.

Thanks!

**Comment by vihanb** [comment]
Hm, do you know if resetting the echo on program exit would work? I am not able to reproduce it. (could you tell me what terminal you are using)

**Comment by CharlesAMoss** [comment]
terminal: bash on osx

No luck yet with getting it to reset on exit from inside but I'll keep trying.

**Comment by vihanb** [comment]
what version of macOS are you on? I am on 10.11.6, and no problem on Terminal.app, which is weird :/

**Comment by CharlesAMoss** [comment]
10.11.6 here as well.

**Comment by vihanb** [comment]
Could you perhaps show me the code that is causing the problem, or if not possible a screenshot of the issue?

**Comment by CharlesAMoss** [comment]
Sure ... here is a simplified version of the code. 

https://github.com/CharlesAMoss/pick-a-card

![screen shot 2017-03-20 at 11 12 18 pm](https://cloud.githubusercontent.com/assets/1514659/24135018/0155e954-0dc5-11e7-9cc0-20057a4a588e.png)

-- discription of screen shot --
- I run the program with "node index.js", 
- I am prompted, 
- I type "draw", 
- the program ends, 
- I type "foobar" (since echo is off it does not print), 
- I hit enter it says "-bash: foobar: command not found", 
- I type "stty echo" enter (turns echo on), 
- I type "foobar" again this time you can see it. 

Hope this helps.

**Comment by yoavg-at-comigo** [comment]
At index.js simply modifying:
`sync_prompt.set_echo(false);`
to
`sync_prompt.set_echo(true);`

Fixes the issue for me

**Comment by vihanb** [comment]
I've changed this with @yoavg-at-comigo's changes in v1.0.3 (on npm now),  hopefully that fixes your issue

**Comment by CharlesAMoss** [comment]
Thanks this has fixed my issue.
