### ISSUE TITLE
fails to install on Windows10 due to some msbuild error

### ISSUE THREAD

**Issue by CarstenKoenig** [cheddar-lang/syncprompt#2]
When I try to install this globally or locally I get this error:

```shell
> syncprompt@2.0.0 install ...project\node_modules\syncprompt
> node-gyp rebuild


...project\node_modules\syncprompt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
MSBUILD : error MSB4025: Die Projektdatei konnte nicht geladen werden. Das Stammelement ist nicht vorhanden.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ...project\src\Elm\node_modules\syncprompt
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! syncprompt@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the syncprompt@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

this is the log: [2018-11-19T05_21_02_126Z-debug.log](https://github.com/cheddar-lang/syncprompt/files/2593898/2018-11-19T05_21_02_126Z-debug.log)

---

Note: I actually need this as a dependency for `elm-upgrade`

**Comment by vihanb** [comment]
I'm not familiar with msbuild/windows toolchain but from what I can tell looks like node-gyp on windows might require some additional C++ items to be installed?

Looking online try running the following:

```bash
npm install -g --production windows-build-tools
```

don't have a windows system so I can't test— any input from anyone who uses windows is appreciated

**Comment by rm2fpt** [comment]
Hi. I tried the command above but I conitnue to receive an error when I try to install syncpro on Windows:

`C:\WINDOWS\system32>npm i syncprompt

> syncprompt@2.0.0 install C:\WINDOWS\system32\node_modules\syncprompt
> node-gyp rebuild


C:\WINDOWS\system32\node_modules\syncprompt>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  sync_prompt.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\sync_prompt.cc': No such file or directory [C:\WINDOWS\syste
m32\node_modules\syncprompt\build\sync_prompt.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\syncprompt
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v `v3.8.0
