### ISSUE TITLE
Error installing on windows 10

### ISSUE THREAD

**Issue by rm2fpt** [cheddar-lang/syncprompt#3]
Hi.

I'm trying to install this package on Windows 10, but throws an error during installation:

C:\WINDOWS\system32>npm i syncprompt

> syncprompt@2.0.0 install C:\WINDOWS\system32\node_modules\syncprompt
> node-gyp rebuild

C:\WINDOWS\system32\node_modules\syncprompt>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax

Can anyone help me. I need this package beacause is the only sync input that works on coderunner autograder from coderunner.org.nz.

Thx

**Comment by vihanb** [comment]
This looks like python issue it looks like node-gyp is using python 3 instead of 2

**Comment by rm2fpt** [comment]
Hi @vihanb.

I run the npm install -g --production windows-build-tools as you suggested in https://github.com/cheddar-lang/syncprompt/issues/2#issuecomment-473778400 and apparentelly it worked.
I use this package because its the onçy one that work with coderrunner (coderunner.org.cz). First I tried to work with readline-sync but the tty mode do not allow.

I hope you continue to mantain this package.
Thx.

``

**Comment by vihanb** [comment]
The latest versions of node-gyp support python3 in addition. To anyone in the future having this issue, feel free to open an issue with your operating system, and python versions/alises.
